version: '3'
services:
  nginx-rtmp:
    build: .
    container_name: tiangolo/nginx-rtmp
    ports:
      - "1935:1935"    # Porta RTMP para enviar fluxo
      - "80:80"    # Porta HTTP para servir HLS
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./hls:/var/www/html/hls