# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      with: 
       clean: true
    - run: echo "NEXT_PUBLIC_HLS=${{ secrets.NEXT_PUBLIC_HLS }}" > .env
    - run: sudo mkdir hls
    - run: sudo chmod -R 777 ./hls
    - run: npm install
    - run: npm run build
    - run: docker compose down --volumes
    - run: docker compose up -d


    
